# environment.yml
name: speech_circuits
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchaudio
  - numpy
  - pandas
  - matplotlib
  - scipy
  - pip
  - pytest
  - pytest-cov
  - pytest-xdist
  - ipykernel
  - jupyter
  - pip:
    - transformers
    - datasets
    - librosa
    - tqdm
    - git+https://github.com/neelnanda-io/TransformerLens
